do $$
begin
  if not exists (select 1 from pg_type where typname = 'chat_type') then
    create type public.chat_type as enum ('direct', 'group', 'broadcast');
  end if;

  if not exists (select 1 from pg_type where typname = 'chat_member_role') then
    create type public.chat_member_role as enum ('admin', 'member');
  end if;
end $$;

do $$
begin
  if exists (
    select 1
    from pg_type t
    join pg_namespace n on n.oid = t.typnamespace
    where n.nspname = 'public'
      and t.typname = 'notification_type'
  ) then
    alter type public.notification_type add value if not exists 'chat.message_received';
    alter type public.notification_type add value if not exists 'chat.mention';
    alter type public.notification_type add value if not exists 'designer.asset_ready';
  end if;
end $$;

create table if not exists public.chats (
  id uuid primary key default gen_random_uuid(),
  org_id uuid not null references public.orgs(id) on delete cascade,
  name text,
  type public.chat_type not null default 'direct',
  allow_replies boolean not null default true,
  created_by uuid not null references public.profiles(id),
  created_at timestamptz not null default now()
);

create table if not exists public.chat_members (
  id bigint generated by default as identity primary key,
  chat_id uuid not null references public.chats(id) on delete cascade,
  user_id uuid not null references public.profiles(id),
  role public.chat_member_role not null default 'member',
  joined_at timestamptz not null default now(),
  unique (chat_id, user_id)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  chat_id uuid not null references public.chats(id) on delete cascade,
  sender_id uuid not null references public.profiles(id),
  message text not null,
  attachments jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_message_mentions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.chat_messages(id) on delete cascade,
  type text not null check (type in ('user', 'all')),
  mentioned_user_id uuid references public.profiles(id),
  raw_label text
);

create index if not exists chat_members_user_id_joined_at_idx
  on public.chat_members (user_id, joined_at desc);

create index if not exists chat_messages_chat_id_created_at_idx
  on public.chat_messages (chat_id, created_at desc);

create index if not exists chat_message_mentions_message_id_idx
  on public.chat_message_mentions (message_id);

alter table public.chats enable row level security;
alter table public.chat_members enable row level security;
alter table public.chat_messages enable row level security;
alter table public.chat_message_mentions enable row level security;

create or replace function public.is_chat_member(p_chat_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = p_chat_id
      and cm.user_id = p_user_id
  );
$$;

create or replace function public.is_chat_admin(p_chat_id uuid, p_user_id uuid default auth.uid())
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = p_chat_id
      and cm.user_id = p_user_id
      and cm.role = 'admin'
  );
$$;

create or replace function public.create_chat_message_with_mentions(
  p_chat_id uuid,
  p_sender_id uuid,
  p_message text,
  p_attachments jsonb default null,
  p_mentions jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_message_id bigint;
  v_mention jsonb;
begin
  if not exists (
    select 1
    from public.chat_members cm
    where cm.chat_id = p_chat_id
      and cm.user_id = p_sender_id
  ) then
    raise exception 'sender is not a chat member' using errcode = '42501';
  end if;

  insert into public.chat_messages (chat_id, sender_id, message, attachments)
  values (p_chat_id, p_sender_id, p_message, p_attachments)
  returning id into v_message_id;

  if jsonb_typeof(coalesce(p_mentions, '[]'::jsonb)) = 'array' then
    for v_mention in select * from jsonb_array_elements(coalesce(p_mentions, '[]'::jsonb))
    loop
      insert into public.chat_message_mentions (
        message_id,
        type,
        mentioned_user_id,
        raw_label
      )
      values (
        v_message_id,
        coalesce(v_mention->>'type', 'user'),
        nullif(v_mention->>'userId', '')::uuid,
        nullif(v_mention->>'label', '')
      );
    end loop;
  end if;

  return v_message_id;
end;
$$;

create or replace function public.get_unread_chat_notifications(p_user_id uuid)
returns table (
  chat_id uuid,
  unread_count bigint,
  last_notification_at timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
  select
    (n.metadata->>'chatId')::uuid as chat_id,
    count(*)::bigint as unread_count,
    max(n.created_at) as last_notification_at
  from public.notifications n
  where n.user_id = p_user_id
    and n.read_at is null
    and n.type::text = 'chat.message_received'
    and n.metadata ? 'chatId'
  group by (n.metadata->>'chatId')::uuid;
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chats' and policyname = 'chat members can read chats'
  ) then
    create policy "chat members can read chats"
      on public.chats for select
      using (public.is_chat_member(id, auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_members' and policyname = 'chat members can read memberships'
  ) then
    create policy "chat members can read memberships"
      on public.chat_members for select
      using (public.is_chat_member(chat_id, auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_messages' and policyname = 'chat members can read messages'
  ) then
    create policy "chat members can read messages"
      on public.chat_messages for select
      using (public.is_chat_member(chat_id, auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'chat_message_mentions' and policyname = 'chat members can read mentions'
  ) then
    create policy "chat members can read mentions"
      on public.chat_message_mentions for select
      using (
        exists (
          select 1
          from public.chat_messages cm
          where cm.id = message_id
            and public.is_chat_member(cm.chat_id, auth.uid())
        )
      );
  end if;
end $$;
